### ISSUE TITLE
Post compatible with dataframe 

### ISSUE THREAD

**Issue by kitbenjamin** [Urban-Meteorology-Reading/urbisphereAtmOapi#1]
At the moment the data needs to be formatted as a dictionary when posting it e.g. 

https://github.com/Urban-Meteorology-Reading/urbisphereFuns/blob/39c557e37c65146095b990546f6f3921571093ce/urbisphereFuns/urbisphere_data_functions.py#L165-L196

It would be cool to have a function where you submit a dataframe (e.g. with cols TIMESTAMP, post_type, v_id, import_table, import_site.... ) which parses the dataframe into dictionary format.

**Comment by willmorrison1** [comment]
I think this is a requirement, not an enhancement.

**Comment by kitbenjamin** [comment]
This is the case after latest restructure 876a9a9
