### ISSUE TITLE
data_from_db: large number of v_ids causes GET request to fail

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/urbisphereAtmOapi#13]
I think the current method is failing because the request string is too long. Where `meta_df_filtered_file_type` has ~ 5500 v_ids, the following fails:
``` py
all_meta.set_meta(meta_df_filtered_file_type)
data = all_meta.data_from_db(startdate=starttime,
                                     enddate=endtime)

  File "C:\Users\willm\anaconda3\envs\py36\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value
```
but this is OK:
``` py
all_meta.set_meta(meta_df_filtered_file_type[:100])
data = all_meta.data_from_db(startdate=starttime,
                                     enddate=endtime)
```

1) hard to reproduce the exact get data request url in the current code. in addition to:
``` py
dat = all_meta.data_from_db(startdate=starttime,
                                     enddate=endtime)
<urbisphereAtmOapi.obsdata.ObsData at 0x27133582ba8>
```
suggest adding this so the url params can be easily inspected
``` py
url_str = all_meta.data_from_db_urlstr(startdate=starttime,
                                     enddate=endtime)
"?startdate=2020-11-08+12%3A58%3A38&enddate=2020-11-08+13%3A28%3A38&v_ids=9628%2C9629"
```
2) suggest GET url has version range option e.g. the following url requests all v_ids from 0->1000, 4565->5555 and also v_ids 1001, 1004 and 1008 [sic]: `?v_id_range=(0,1000);(4565,5555)&?v_id=1001,1004,1008`

**Comment by willmorrison1** [comment]
was not very reproducible from me. will keep my eye on this and try to reproduce.

**Comment by willmorrison1** [comment]
can't reproduce

**Comment by kitbenjamin** [comment]
http://urbisphere.uni-freiburg.de/addemp/API/api//get_data_non_readable.php/?startdate=2021-05-20%2000:00:00&enddate=2021-05-20%2001:00:00&v_ids=14261.0,15031.0,14262.0,15032.0,14263.0,15033.0,14264.0,15034.0,14265.0,15035.0,15036.0,14266.0,14267.0,15037.0,15038.0,14268.0,15039.0,14269.0,15040.0,14270.0,15041.0,14271.0,15042.0,14272.0,15043.0,14273.0,15044.0,14274.0,14275.0,15045.0,14276.0,15046.0,14277.0,15047.0,14278.0,15048.0,14279.0,15049.0,14280.0,15050.0,14281.0,15051.0,15052.0,14282.0,15053.0,14283.0,15054.0,14284.0,14285.0,15055.0,14286.0,15056.0,15057.0,14287.0,14288.0,15058.0,14289.0,15059.0,14290.0,15060.0,14291.0,15061.0,15062.0,14292.0,15063.0,14293.0,14294.0,15064.0,15065.0,14295.0,15066.0,14296.0,14297.0,15067.0,14298.0,15068.0,14299.0,15069.0,14300.0,15070.0,14301.0,15071.0,15072.0,14302.0,14303.0,15073.0,14304.0,15074.0,15075.0,14305.0,14306.0,15076.0,15077.0,14307.0,15078.0,14308.0,15079.0,14309.0,15080.0,14310.0,14311.0,15081.0,14312.0,15082.0,15083.0,14313.0,15084.0,14314.0,15085.0,14315.0,14316.0,15086.0,15087.0,14317.0,14318.0,15088.0,14319.0,15089.0,14320.0,15090.0,14321.0,15091.0,14322.0,15092.0,15093.0,14323.0,15094.0,14324.0,15095.0,14325.0,14326.0,15096.0,14327.0,15097.0,14328.0,15098.0,14329.0,15099.0,14330.0,15100.0,14331.0,15101.0,14332.0,15102.0,14333.0,15103.0,14334.0,15104.0,14335.0,15105.0,15106.0,14336.0,15107.0,14337.0,15108.0,14338.0,15109.0,14339.0,14340.0,15110.0,15111.0,14341.0,15112.0,14342.0,15113.0,14343.0,14344.0,15114.0,14345.0,15115.0,14346.0,15116.0,14347.0,15117.0,14348.0,15118.0,14349.0,15119.0,14350.0,15120.0,14351.0,15121.0,14352.0,15122.0,14353.0,15123.0,14354.0,15124.0,14355.0,15125.0,14356.0,15126.0,14357.0,15127.0,14358.0,15128.0,14359.0,15129.0,14360.0,15130.0,14361.0,15131.0,14362.0,15132.0,14363.0,15133.0,15134.0,14364.0,15135.0,14365.0,14366.0,15136.0,14367.0,15137.0,15138.0,14368.0,14369.0,15139.0,15140.0,14370.0,14371.0,15141.0,14372.0,15142.0,15143.0,14373.0,14374.0,15144.0,14375.0,15145.0,15146.0,14376.0,14377.0,15147.0,14378.0,15148.0,15149.0,14379.0,15150.0,14380.0,14381.0,15151.0,15152.0,14382.0,15153.0,14383.0,14384.0,15154.0,14385.0,15155.0,15156.0,14386.0,15157.0,14387.0,15158.0,14388.0,15159.0,14389.0,15160.0,14390.0,15161.0,14391.0,15162.0,14392.0,14393.0,15163.0,14394.0,15164.0,14395.0,15165.0,15166.0,14396.0,14397.0,15167.0,14398.0,15168.0,14399.0,15169.0,14400.0,15170.0,15171.0,14401.0,14402.0,15172.0,14403.0,15173.0,14404.0,15174.0,14405.0,15175.0,14406.0,15176.0,14407.0,15177.0,14408.0,15178.0,15179.0,14409.0,14410.0,15180.0,14411.0,15181.0,14412.0,15182.0,15183.0,14413.0,14414.0,15184.0,14415.0,15185.0,14416.0,15186.0,14417.0,15187.0,15188.0,14418.0,14419.0,15189.0,14420.0,15190.0,15191.0,14421.0,14422.0,15192.0,14423.0,15193.0,15194.0,14424.0,14425.0,15195.0,15196.0,14426.0,15197.0,14427.0,15198.0,14428.0,15199.0,14429.0,14430.0,15200.0,14431.0,15201.0,14432.0,15202.0,14433.0,15203.0,14434.0,15204.0,14435.0,15205.0,14436.0,15206.0,14437.0,15207.0,14438.0,15208.0,14439.0,15209.0,14440.0,15210.0,15211.0,14441.0,15212.0,14442.0,15213.0,14443.0,15214.0,14444.0,15215.0,14445.0,15216.0,14446.0,15217.0,14447.0,15218.0,14448.0,15219.0,14449.0,15220.0,14450.0,15221.0,14451.0,15222.0,14452.0,15223.0,14453.0,15224.0,14454.0,15225.0,14455.0,15226.0,14456.0,15227.0,14457.0,15228.0,14458.0,15229.0,14459.0,15230.0,14460.0,15231.0,14461.0,14462.0,15232.0,14463.0,15233.0,14464.0,15234.0,14465.0,15235.0,14466.0,15236.0,14467.0,15237.0,15238.0,14468.0,15239.0,14469.0,15240.0,14470.0,14471.0,15241.0,14472.0,15242.0,14473.0,15243.0,15244.0,14474.0,14475.0,15245.0,15246.0,14476.0,15247.0,14477.0,14478.0,15248.0,14479.0,15249.0,14480.0,15250.0,15251.0,14481.0,15252.0,14482.0,15253.0,14483.0,14484.0,15254.0,14485.0,15255.0,15256.0,14486.0,14487.0,15257.0,14488.0,15258.0,14489.0,15259.0,14490.0,15260.0,14491.0,15261.0,14492.0,15262.0,14493.0,15263.0,15264.0,14494.0,14495.0,15265.0,14496.0,15266.0,14497.0,15267.0,15268.0,14498.0,15269.0,14499.0,15270.0,14500.0,15271.0,14501.0,15272.0,14502.0,15273.0,14503.0,14504.0,15274.0,14505.0,15275.0,14506.0,15276.0,15277.0,14507.0,14508.0,15278.0,14509.0,15279.0,15280.0,14510.0,14511.0,15281.0,15282.0,14512.0,14513.0,15283.0,15284.0,14514.0,15285.0,14515.0,15286.0,14516.0,14517.0,15287.0,15288.0,14518.0,15289.0,14519.0,15290.0,14520.0,14521.0,15291.0,14522.0,15292.0,14523.0,15293.0,15294.0,14524.0,14525.0,15295.0,14526.0,15296.0,15297.0,14527.0,14528.0,15298.0,14529.0,15299.0,15300.0,14530.0,15301.0,14531.0,15302.0,14532.0,15303.0,14533.0,15304.0,14534.0,15305.0,14535.0,15306.0,14536.0,15307.0,14537.0,15308.0,14538.0,14539.0,15309.0,14540.0,15310.0,14541.0,15311.0,15312.0,14542.0,15313.0,14543.0,15314.0,14544.0,15315.0,14545.0,15316.0,14546.0,14547.0,15317.0,15318.0,14548.0,15319.0,14549.0,14550.0,15320.0,14551.0,15321.0,14552.0,15322.0,15323.0,14553.0,15324.0,14554.0,14555.0,15325.0,14556.0,15326.0,15327.0,14557.0,14558.0,15328.0,15329.0,14559.0,15330.0,14560.0,15331.0,14561.0,15332.0,14562.0,15333.0,14563.0,15334.0,14564.0,14565.0,15335.0,15336.0,14566.0,15337.0,14567.0,14568.0,15338.0,14569.0,15339.0,14570.0,15340.0,14571.0,15341.0,15342.0,14572.0,15343.0,14573.0,15344.0,14574.0,15345.0,14575.0,15346.0,14576.0,14577.0,15347.0,15348.0,14578.0,14579.0,15349.0,15350.0,14580.0,15351.0,14581.0,14582.0,15352.0,14583.0,15353.0,14584.0,15354.0,14585.0,15355.0,14586.0,15356.0,14587.0,15357.0,14588.0,15358.0,14589.0,15359.0,14590.0,15360.0,14591.0,15361.0,14592.0,15362.0,14593.0,15363.0,15364.0,14594.0,14595.0,15365.0,14596.0,15366.0,15367.0,14597.0,14598.0,15368.0,15369.0,14599.0,15370.0,14600.0,15371.0,14601.0,15372.0,14602.0,15373.0,14603.0,14604.0,15374.0,15375.0,14605.0,15376.0,14606.0,15377.0,14607.0,15378.0,14608.0,15379.0,14609.0,15380.0,14610.0,15381.0,14611.0,14612.0,15382.0,14613.0,15383.0,15384.0,14614.0,15385.0,14615.0,15386.0,14616.0,14617.0,15387.0,14618.0,15388.0,14619.0,15389.0,14620.0,15390.0,15391.0,14621.0,15392.0,14622.0,14623.0,15393.0,14624.0,15394.0,14625.0,15395.0,14626.0,15396.0,14627.0,15397.0,15398.0,14628.0,15399.0,14629.0,15400.0,14630.0,15401.0,14631.0,15402.0,14632.0,15403.0,14633.0,15404.0,14634.0,15405.0,14635.0,14636.0,15406.0,14637.0,15407.0,14638.0,15408.0,14639.0,15409.0,15410.0,14640.0,14641.0,15411.0,15412.0,14642.0,15413.0,14643.0,15414.0,14644.0,15415.0,14645.0,14646.0,15416.0,14647.0,15417.0,15418.0,14648.0,15419.0,14649.0,14650.0,15420.0,15421.0,14651.0,15422.0,14652.0,15423.0,14653.0,14654.0,15424.0,14655.0,15425.0,14656.0,15426.0,15427.0,14657.0,15428.0,14658.0,14659.0,15429.0,14660.0,15430.0,14661.0,15431.0,15432.0,14662.0,14663.0,15433.0,15434.0,14664.0,14665.0,15435.0,15436.0,14666.0,14667.0,15437.0,15438.0,14668.0,15439.0,14669.0,15440.0,14670.0,15441.0,14671.0,15442.0,14672.0,15443.0,14673.0,14674.0,15444.0,15445.0,14675.0,14676.0,15446.0,14677.0,15447.0,15448.0,14678.0,15449.0,14679.0,15450.0,14680.0,14681.0,15451.0,14682.0,15452.0,14683.0,15453.0,15454.0,14684.0,15455.0,14685.0,14686.0,15456.0,15457.0,14687.0,15458.0,14688.0,15459.0,14689.0,15460.0,14690.0,15461.0,14691.0,14692.0,15462.0,15463.0,14693.0,15464.0,14694.0,15465.0,14695.0,14696.0,15466.0,15467.0,14697.0,15468.0,14698.0,14699.0,15469.0,15470.0,14700.0,14701.0,15471.0,15472.0,14702.0,14703.0,15473.0,15474.0,14704.0,14705.0,15475.0,14706.0,15476.0,14707.0,15477.0,15478.0,14708.0,15479.0,14709.0,15480.0,14710.0,15481.0,14711.0,15482.0,14712.0,15483.0,14713.0,14714.0,15484.0,14715.0,15485.0,15486.0,14716.0,15487.0,14717.0,14718.0,15488.0,15489.0,14719.0,15490.0,14720.0,15491.0,14721.0,15492.0,14722.0,15493.0,14723.0,14724.0,15494.0,15495.0,14725.0,15496.0,14726.0,15497.0,14727.0,14728.0,15498.0,14729.0,15499.0,15500.0,14730.0,15501.0,14731.0,14732.0,15502.0,15503.0,14733.0,14734.0,15504.0,15505.0,14735.0,15506.0,14736.0,15507.0,14737.0,15508.0,14738.0,15509.0,14739.0,14740.0,15510.0,15511.0,14741.0,15512.0,14742.0,15513.0,14743.0,15514.0,14744.0,15515.0,14745.0,14746.0,15516.0,15517.0,14747.0,14748.0,15518.0,15519.0,14749.0,14750.0,15520.0,15521.0,14751.0,15522.0,14752.0,14753.0,15523.0,14754.0,15524.0,14755.0,15525.0,14756.0,15526.0,14757.0,15527.0,14758.0,15528.0,15529.0,14759.0,15530.0,14760.0,15531.0,14761.0,14762.0,15532.0,14763.0,15533.0,15534.0,14764.0,14765.0,15535.0,14766.0,15536.0,14767.0,15537.0,14768.0,15538.0,14769.0,15539.0,15540.0,14770.0,14771.0,15541.0,15542.0,14772.0,14773.0,15543.0,15544.0,14774.0,15545.0,14775.0,15546.0,14776.0,14777.0,15547.0,14778.0,15548.0,14779.0,15549.0,15550.0,14780.0,14781.0,15551.0,14782.0,15552.0,15553.0,14783.0,14784.0,15554.0,14785.0,15555.0,14786.0,15556.0,14787.0,15557.0,15558.0,14788.0,15559.0,14789.0,15560.0,14790.0,14791.0,15561.0,14792.0,15562.0,14793.0,15563.0,14794.0,15564.0,15565.0,14795.0,15566.0,14796.0,14797.0,15567.0,14798.0,15568.0,14799.0,15569.0,14800.0,15570.0,15571.0,14801.0,14802.0,15572.0,14803.0,15573.0,14804.0,15574.0,15575.0,14805.0,15576.0,14806.0,15577.0,14807.0,14808.0,15578.0,15579.0,14809.0,14810.0,15580.0,15581.0,14811.0,15582.0,14812.0,14813.0,15583.0,15584.0,14814.0,15585.0,14815.0,15586.0,14816.0,15587.0,14817.0,15588.0,14818.0,14819.0,15589.0,14820.0,15590.0,15591.0,14821.0,14822.0,15592.0,14823.0,15593.0,14824.0,15594.0,14825.0,15595.0,15596.0,14826.0,15597.0,14827.0,15598.0,14828.0,15599.0,14829.0,14830.0,15600.0,14831.0,15601.0,15602.0,14832.0,15603.0,14833.0,15604.0,14834.0,15605.0,14835.0,15606.0,14836.0,14837.0,15607.0,14838.0,15608.0,14839.0,15609.0,15610.0,14840.0,15611.0,14841.0,15612.0,14842.0,14843.0,15613.0,14844.0,15614.0,15615.0,14845.0,14846.0,15616.0,15617.0,14847.0,15618.0,14848.0,15619.0,14849.0,14850.0,15620.0,14851.0,15621.0,14852.0,15622.0,15623.0,14853.0,14854.0,15624.0,15625.0,14855.0,15626.0,14856.0,15627.0,14857.0,14858.0,15628.0,14859.0,15629.0,14860.0,15630.0,14861.0,15631.0,14862.0,15632.0,14863.0,15633.0,15634.0,14864.0,14865.0,15635.0,14866.0,15636.0,14867.0,15637.0,15638.0,14868.0,14869.0,15639.0,15640.0,14870.0,15641.0,14871.0,15642.0,14872.0,14873.0,15643.0,14874.0,15644.0,15645.0,14875.0,14876.0,15646.0,15647.0,14877.0,15648.0,14878.0,15649.0,14879.0,15650.0,14880.0,15651.0,14881.0,15652.0,14882.0,14883.0,15653.0,15654.0,14884.0,14885.0,15655.0,14886.0,15656.0,15657.0,14887.0,14888.0,15658.0,14889.0,15659.0,15660.0,14890.0,14891.0,15661.0,15662.0,14892.0,14893.0,15663.0,15664.0,14894.0,14895.0,15665.0,14896.0,15666.0,14897.0,15667.0,14898.0,15668.0,14899.0,15669.0,15670.0,14900.0,14901.0,15671.0,15672.0,14902.0,15673.0,14903.0,15674.0,14904.0,14905.0,15675.0,14906.0,15676.0,14907.0,15677.0,15678.0,14908.0,14909.0,15679.0,14910.0,15680.0,15681.0,14911.0,14912.0,15682.0,14913.0,15683.0,14914.0,15684.0,14915.0,15685.0,15686.0,14916.0,15687.0,14917.0,15688.0,14918.0,14919.0,15689.0,14920.0,15690.0,14921.0,15691.0,14922.0,15692.0,15693.0,14923.0,15694.0,14924.0,15695.0,14925.0,14926.0,15696.0,14927.0,15697.0,14928.0,15698.0,15699.0,14929.0,15700.0,14930.0,15701.0,14931.0,15702.0,14932.0,15703.0,14933.0,14934.0,15704.0,14935.0,15705.0,15706.0,14936.0,14937.0,15707.0,15708.0,14938.0,15709.0,14939.0,15710.0,14940.0,14941.0,15711.0,15712.0,14942.0,14943.0,15713.0,14944.0,15714.0,15715.0,14945.0,15716.0,14946.0,14947.0,15717.0,15718.0,14948.0,14949.0,15719.0,14950.0,15720.0,14951.0,15721.0,14952.0,15722.0,14953.0,15723.0,14954.0,15724.0,15725.0,14955.0,15726.0,14956.0,14957.0,15727.0,15728.0,14958.0,14959.0,15729.0,14960.0,15730.0,14961.0,15731.0,14962.0,15732.0,14963.0,15733.0,15734.0,14964.0,14965.0,15735.0,15736.0,14966.0,15737.0,14967.0,15738.0,14968.0,14969.0,15739.0,14970.0,15740.0,14971.0,15741.0,15742.0,14972.0,15743.0,14973.0,14974.0,15744.0,15745.0,14975.0,14976.0,15746.0,14977.0,15747.0,14978.0,15748.0,14979.0,15749.0,15750.0,14980.0,15751.0,14981.0,14982.0,15752.0,15753.0,14983.0,14984.0,15754.0,14985.0,15755.0,14986.0,15756.0,15757.0,14987.0,15758.0,14988.0,15759.0,14989.0,14990.0,15760.0,14991.0,15761.0,15762.0,14992.0,14993.0,15763.0,14994.0,15764.0,14995.0,15765.0,15766.0,14996.0,14997.0,15767.0,15768.0,14998.0,15769.0,14999.0,15770.0,15000.0,15001.0,15771.0,15002.0,15772.0,15003.0,15773.0,15774.0,15004.0,15005.0,15775.0,15776.0,15006.0,15007.0,15777.0,15778.0,15008.0,15009.0,15779.0,15780.0,15010.0,15781.0,15011.0,15782.0,15012.0,15013.0,15783.0,15784.0,15014.0,15785.0,15015.0,15786.0,15016.0,15017.0,15787.0,15788.0,15018.0,15789.0,15019.0,15790.0,15020.0,15791.0,15021.0,15792.0,15022.0,15793.0,15023.0,15794.0,15024.0,15025.0,15795.0,15796.0,15026.0,15797.0,15027.0,15798.0,15028.0,15799.0,15029.0,15030.0,15800.0

Does the job.

A few possible workarounds:
- increase the length limit by changing server configuration
- submit versions in "chunks"
- Submit it as a post request and put the versions in the body of the request (seems a bit dodgy as we're not posting anything)

Any thoughts @willmorrison1

**Comment by willmorrison1** [comment]
Why not:

> suggest GET url has version range option e.g. the following url requests all v_ids from 0->1000, 4565->5555 and also v_ids 1001, 1004 and 1008 [sic]: ?v_id_range=(0,1000);(4565,5555)&?v_id=1001,1004,1008

**Comment by kitbenjamin** [comment]
^ done in the api. Now needs to be impletemented here. AllMeta.from_db() should detect consecutive v_ids and parse them in the format:

```
http://localhost/addemp/API/api/get_data_non_readable.php?startdate=2021-05-20 00:00:00&enddate=2021-05-20 01:00:00 

&v_ids=v_id1,v_id_n&v_id_range=v_id_start_1:v_id_end_1,v_id_start_2:v_id_end_2
```

**Comment by willmorrison1** [comment]
nice. I think will be very useful/critical for large data downloads
