### ISSUE TITLE
check_duplicate_time_ids is very slow

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/urbisphereAtmOapi#15]
https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi/blob/211f1e9dbef132f155649601715dff7d3db8fe5f/urbisphereAtmOapi/obsdata.py#L102

for data.data.shape
Out[6]: (12000, 3)

check duplciates takes 9 s 
![image](https://user-images.githubusercontent.com/51793934/117970888-1f93ba80-b321-11eb-877d-27bd7630ae9c.png)

must be faster

**Comment by kitbenjamin** [comment]
Done in [latest commit](https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi/commit/211f1e9dbef132f155649601715dff7d3db8fe5f)
