### ISSUE TITLE
meta.from_db fails if database table is empty

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/urbisphereAtmOapi#19]
e.g. http://urbisphere.uni-freiburg.de/addemp/API/api//get_data_non_readable.php/?startdate=2021-05-21+07%3A00%3A00%2B00%3A00&enddate=2021-05-21+15%3A00%3A00%2B00%3A00&v_ids=15788%2C15789%2C15790%2C15791

`Getting data failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'weather_data.gregor-ceil-5min' doesn't exist{"TIMESTAMP":[]}`

i dont think from_db should return an error, because we're now checking what already exists before putting new data up

**Comment by kitbenjamin** [comment]
Now fixed- @willmorrison1 feel free to re-open if you're not happy with this solution
