### ISSUE TITLE
Add comand to upgrade package in Readme

### ISSUE THREAD

**Issue by georgestanley** [Urban-Meteorology-Reading/urbisphereAtmOapi#25]
Please add a pip command in README to upgrade existing installation on a user's machine
I used the below command but not sure if it's the correct one.
`pip install --upgrade git+https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi.git
`

**Comment by willmorrison1** [comment]
Hi @georgestanley. Thanks for the suggestion. I updated this here https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi/commit/911ed62a38580e41bf6c8d378ff01a02226e6245

You also now have write access to this repo. 

Whenever anything is unclear with the code or documentation please continue to write issues and do pull requests to help improve the package
