### ISSUE TITLE
`def __post_call`: suggest making a post sub-module where ```_post_call()``` and ```_post_to_db``` are in post.py

### ISSUE THREAD

**Issue by kitbenjamin** [Urban-Meteorology-Reading/urbisphereAtmOapi#3]
`def __post_call`: suggest making a post sub-module where ```_post_call()``` and ```_post_to_db``` are in post.py

```
import urbisphereAtmOapi.post

post._post_call(obs_data)

```
etc

it partitions the code and allows us to work on different things. Sub-moduling can be applied elsewhere in this code.

_Originally posted by @willmorrison1 in https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi/pull/2#discussion_r616000609_

**Comment by willmorrison1** [comment]
thanks. to clarify:

`post._post_call(obs_data)` is inside the `.post_to_db()` method. 

other submodules to suggest off the top of my head: Meta.py, Data.py, which have all relevant classes defined within.

**Comment by willmorrison1** [comment]
good example is in geopandas, where a read data method [".from_file()"](https://github.com/geopandas/geopandas/blob/f4a9763f90d65dea21e2e628e60326e27ca13576/geopandas/geodataframe.py#L455) is actually [one line of code](https://github.com/geopandas/geopandas/blob/f4a9763f90d65dea21e2e628e60326e27ca13576/geopandas/geodataframe.py#L503) and links to its ["io" (input/output) submodule](https://github.com/geopandas/geopandas/blob/f4a9763f90d65dea21e2e628e60326e27ca13576/geopandas/geodataframe.py#L17) that deals with the details.

**Comment by kitbenjamin** [comment]
Done in 876a9a9
